#!/usr/bin/env python3
"""
Night Shift Research Queue Processor
Processes sherlock_research jobs from Night Shift queue

Constitutional Authority: Prism Review #3 - IMP_006
Purpose: Enable research job execution pipeline
"""

import json
import logging
import sys
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Any

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

QUEUE_FILE = Path("/home/johnny5/Johny5Alive/j5a-nightshift/ops/queue/nightshift_jobs.json")
EVIDENCE_DIR = Path("/home/johnny5/Sherlock/evidence")


class ResearchQueueProcessor:
    """Process sherlock_research jobs from Night Shift queue"""

    def __init__(self, queue_file: Path = QUEUE_FILE):
        self.queue_file = queue_file
        self.processed_count = 0
        self.failed_count = 0
        self.skipped_count = 0

    def load_queue(self) -> List[Dict[str, Any]]:
        """Load jobs from queue file"""
        if not self.queue_file.exists():
            logger.error(f"Queue file not found: {self.queue_file}")
            return []

        with open(self.queue_file, 'r') as f:
            jobs = json.load(f)

        logger.info(f"Loaded {len(jobs)} jobs from queue")
        return jobs

    def save_queue(self, jobs: List[Dict[str, Any]]):
        """Save updated jobs back to queue file"""
        with open(self.queue_file, 'w') as f:
            json.dump(jobs, f, indent=2)

        logger.info(f"Saved {len(jobs)} jobs to queue")

    def process_job(self, job: Dict[str, Any]) -> bool:
        """
        Process a single research job

        Returns True if successful, False otherwise
        """
        job_id = job.get('job_id', 'UNKNOWN')
        target_name = job.get('metadata', {}).get('target_name', 'Unknown')

        try:
            # Get research question
            inputs = job.get('inputs', [])
            if not inputs:
                logger.warning(f"Job {job_id}: No inputs found")
                return False

            question = inputs[0].get('question', '')
            if not question or question == 'No question provided':
                logger.warning(f"Job {job_id}: Invalid question")
                return False

            # Update status to processing
            job['status'] = 'processing'
            job['processing_started_at'] = datetime.now().isoformat()

            logger.info(f"Processing {job_id} - {target_name}")
            logger.info(f"Question: {question[:100]}...")

            # TODO: Execute actual research
            # For now, create placeholder evidence file
            output_path = job.get('outputs', [{}])[0].get('path', '')
            if output_path:
                output_file = Path(output_path)
                output_file.parent.mkdir(parents=True, exist_ok=True)

                # Create placeholder evidence
                evidence_content = f"""# Research: {target_name}

**Question:** {question}

**Generated:** {datetime.now().isoformat()}
**Job ID:** {job_id}
**Status:** Placeholder (awaiting full research synthesis implementation)

## Notes

This is a placeholder evidence file generated by the research queue processor.
Full research synthesis requires integration with:
- Web search capabilities
- LLM synthesis pipeline
- Source verification
- Citation generation

**Next Steps:** Implement full research synthesis pipeline in Phase 2 of IMP_006.
"""

                output_file.write_text(evidence_content)
                logger.info(f"Created placeholder evidence: {output_file}")

            # Update status to completed
            job['status'] = 'completed'
            job['processing_completed_at'] = datetime.now().isoformat()

            return True

        except Exception as e:
            logger.error(f"Job {job_id} failed: {e}", exc_info=True)
            job['status'] = 'failed'
            job['error'] = str(e)
            job['failed_at'] = datetime.now().isoformat()
            return False

    def process_queue(self, max_jobs: int = 10, dry_run: bool = False):
        """
        Process ready jobs from queue

        Args:
            max_jobs: Maximum number of jobs to process in this run
            dry_run: If True, don't actually modify queue or create files
        """
        logger.info("="*70)
        logger.info("RESEARCH QUEUE PROCESSOR STARTING")
        logger.info("="*70)
        logger.info(f"Max jobs to process: {max_jobs}")
        logger.info(f"Dry run: {dry_run}")

        # Load queue
        jobs = self.load_queue()
        if not jobs:
            logger.warning("No jobs in queue")
            return

        # Find ready sherlock_research jobs WITH valid questions
        ready_jobs = []
        for j in jobs:
            if j.get('status') != 'ready' or j.get('type') != 'sherlock_research':
                continue

            # Check for valid question
            inputs = j.get('inputs', [])
            if not inputs:
                continue

            question = inputs[0].get('question', '')
            if question and question != 'No question provided':
                ready_jobs.append(j)

        logger.info(f"Found {len(ready_jobs)} ready sherlock_research jobs with valid questions")

        if not ready_jobs:
            logger.info("No ready jobs to process")
            return

        # Process up to max_jobs
        jobs_to_process = ready_jobs[:max_jobs]
        logger.info(f"Processing {len(jobs_to_process)} jobs")

        for job in jobs_to_process:
            if dry_run:
                job_id = job.get('job_id', 'UNKNOWN')
                target = job.get('metadata', {}).get('target_name', 'Unknown')
                logger.info(f"[DRY RUN] Would process: {job_id} - {target}")
                self.skipped_count += 1
            else:
                success = self.process_job(job)
                if success:
                    self.processed_count += 1
                else:
                    self.failed_count += 1

        # Save updated queue
        if not dry_run:
            self.save_queue(jobs)

        logger.info("="*70)
        logger.info("RESEARCH QUEUE PROCESSOR COMPLETE")
        logger.info("="*70)
        logger.info(f"Processed: {self.processed_count}")
        logger.info(f"Failed: {self.failed_count}")
        logger.info(f"Skipped: {self.skipped_count}")


def main():
    """Main entry point"""
    import argparse

    parser = argparse.ArgumentParser(description='Process Night Shift research queue')
    parser.add_argument('--max-jobs', type=int, default=10,
                       help='Maximum number of jobs to process (default: 10)')
    parser.add_argument('--dry-run', action='store_true',
                       help='Dry run - do not modify queue or create files')
    parser.add_argument('--all', action='store_true',
                       help='Process all ready jobs (ignores --max-jobs)')

    args = parser.parse_args()

    max_jobs = 999999 if args.all else args.max_jobs

    processor = ResearchQueueProcessor()
    processor.process_queue(max_jobs=max_jobs, dry_run=args.dry_run)


if __name__ == '__main__':
    main()
