#!/usr/bin/env python3
"""
FreeCAD Macro Generator for Sherlock Site Characterization

Generates FreeCAD Python macros from freecad_site_inputs.json to create
parametric geometry for underground shelter design.
"""
import os
import json
import logging
from pathlib import Path
from typing import Dict, Any, Optional
from datetime import datetime

logger = logging.getLogger(__name__)


class FreeCADMacroGenerator:
    """
    Generate FreeCAD Python macros for site characterization geometry.
    """

    MACRO_HEADER = '''# FreeCAD Macro - Butte Hill Site Geometry
# Generated by Sherlock GeospatialAgent
# Date: {date}
# Project: {project}
#
# This macro creates parametric geometry for underground shelter design.
# Run in FreeCAD by: Macro -> Macros -> Select this file -> Execute

import FreeCAD as App
import Part
import Draft
from FreeCAD import Vector

# Ensure we have an active document
if App.ActiveDocument is None:
    App.newDocument("ButteHill_Site")

doc = App.ActiveDocument

'''

    MACRO_FOOTER = '''
# Recompute and refresh
doc.recompute()
App.ActiveDocument.recompute()

# Set view to fit all
try:
    import FreeCADGui as Gui
    Gui.ActiveDocument.activeView().viewIsometric()
    Gui.SendMsgToActiveView("ViewFit")
except:
    pass  # GUI may not be available in headless mode

print("Site geometry created successfully!")
print(f"Portal location: {portal_x:.1f}m E, {portal_y:.1f}m N at {portal_elev:.1f}ft elevation")
print(f"Adit length: {adit_length_ft:.1f}ft at {adit_bearing:.1f}° bearing, {adit_grade_pct:.1f}% grade")
'''

    def __init__(self, inputs_json_path: str):
        """
        Initialize generator with site inputs

        Args:
            inputs_json_path: Path to freecad_site_inputs.json
        """
        self.inputs_path = Path(inputs_json_path)

        with open(self.inputs_path) as f:
            self.inputs = json.load(f)

    def generate_macro(self, output_path: str) -> str:
        """
        Generate complete FreeCAD macro

        Args:
            output_path: Path to write .FCMacro file

        Returns:
            Path to generated macro
        """
        meta = self.inputs.get('meta', {})
        site = self.inputs.get('site', {})
        terrain = self.inputs.get('terrain', {})
        subsurface = self.inputs.get('subsurface', {})
        recommendations = self.inputs.get('recommendations', {})
        freecad_params = self.inputs.get('freecad_params', {})

        # Start building macro
        macro = self.MACRO_HEADER.format(
            date=datetime.now().isoformat(),
            project=meta.get('project', 'ButteHill')
        )

        # Add parameters section
        macro += self._generate_parameters_section(freecad_params, recommendations, terrain, subsurface)

        # Add geometry creation
        macro += self._generate_terrain_context()
        macro += self._generate_portal_marker(terrain)
        macro += self._generate_adit_geometry(freecad_params, recommendations)
        macro += self._generate_collar_geometry(freecad_params)
        macro += self._generate_chamber_geometry(freecad_params)
        macro += self._generate_layer_organization()

        # Add footer
        macro += self.MACRO_FOOTER

        # Write macro file
        with open(output_path, 'w') as f:
            f.write(macro)

        logger.info(f"Generated FreeCAD macro: {output_path}")
        return output_path

    def _generate_parameters_section(
        self,
        freecad_params: Dict,
        recommendations: Dict,
        terrain: Dict,
        subsurface: Dict
    ) -> str:
        """Generate parameters section"""
        adit = freecad_params.get('adit', {})
        collar = freecad_params.get('collar', {})
        axis = recommendations.get('adit_axis', {})
        portal = self._get_recommended_portal(terrain, recommendations)

        bedrock = subsurface.get('bedrock_depth_ft', {})

        return f'''
# ============================================================
# PARAMETERS (from freecad_site_inputs.json)
# ============================================================

# Units
UNITS_LENGTH = "{freecad_params.get('units', {}).get('length', 'ft')}"  # ft or m
FT_TO_M = 0.3048  # Conversion factor

# Portal Location (UTM 10N)
portal_x = {portal.get('centroid_xy', {}).get('x_m', 0):.2f}  # meters easting
portal_y = {portal.get('centroid_xy', {}).get('y_m', 0):.2f}  # meters northing
portal_elev = {portal.get('elev_ft', 0):.1f}  # feet

# Adit Axis
adit_bearing = {axis.get('bearing_deg', 0):.1f}  # degrees from north
adit_grade_pct = {axis.get('grade_pct', 2.0):.1f}  # percent downgrade
adit_length_ft = {adit.get('length_ft', 30):.1f}

# Adit Cross-Section
adit_excavation_w_ft = {adit.get('excavation_w_ft', 7.0):.1f}
adit_excavation_h_ft = {adit.get('excavation_h_ft', 8.5):.1f}
adit_clear_w_ft = {adit.get('clear_w_ft', 6.0):.1f}
adit_clear_h_ft = {adit.get('clear_h_ft', 7.0):.1f}
adit_set_spacing_ft = {adit.get('set_spacing_ft', 3.0):.1f}

# Collar
collar_thickness_ft = {collar.get('thickness_ft', 1.0):.1f}
collar_key_into_rock_ft = {collar.get('key_into_rock_ft', 2.0):.1f}

# Bedrock Envelope
bedrock_min_ft = {bedrock.get('min', 0):.1f}
bedrock_likely_ft = {bedrock.get('likely', 0):.1f}
bedrock_max_ft = {bedrock.get('max', 0):.1f}

'''

    def _get_recommended_portal(self, terrain: Dict, recommendations: Dict) -> Dict:
        """Get recommended portal from candidates"""
        rec_id = recommendations.get('recommended_portal_id', '')
        candidates = terrain.get('portal_candidates', [])

        for c in candidates:
            if c.get('id') == rec_id:
                return c

        # Return first candidate or empty
        return candidates[0] if candidates else {'centroid_xy': {'x_m': 0, 'y_m': 0}, 'elev_ft': 0}

    def _generate_terrain_context(self) -> str:
        """Generate terrain context markers"""
        return '''
# ============================================================
# TERRAIN CONTEXT (Reference Markers)
# ============================================================

# Create terrain group
terrain_group = doc.addObject("App::DocumentObjectGroup", "Terrain")

# Portal reference point
portal_point = doc.addObject("Part::Sphere", "PortalPoint")
portal_point.Radius = 1.0  # 1m sphere
portal_point.Placement = App.Placement(
    Vector(portal_x, portal_y, portal_elev * FT_TO_M),
    App.Rotation()
)
terrain_group.addObject(portal_point)

# North arrow (10m long)
north_arrow = Draft.makeLine(
    Vector(portal_x, portal_y, portal_elev * FT_TO_M),
    Vector(portal_x, portal_y + 10, portal_elev * FT_TO_M)
)
north_arrow.Label = "North"
terrain_group.addObject(north_arrow)

'''

    def _generate_portal_marker(self, terrain: Dict) -> str:
        """Generate portal candidate markers"""
        code = '''
# ============================================================
# PORTAL CANDIDATES
# ============================================================

portal_group = doc.addObject("App::DocumentObjectGroup", "PortalCandidates")

'''
        candidates = terrain.get('portal_candidates', [])
        for i, c in enumerate(candidates[:5]):
            x = c.get('centroid_xy', {}).get('x_m', 0)
            y = c.get('centroid_xy', {}).get('y_m', 0)
            elev = c.get('elev_ft', 0)
            cid = c.get('id', f'PC{i+1}')

            code += f'''
# {cid}
portal_{cid} = doc.addObject("Part::Cylinder", "{cid}")
portal_{cid}.Radius = 2.0
portal_{cid}.Height = 0.5
portal_{cid}.Placement = App.Placement(
    Vector({x:.2f}, {y:.2f}, {elev:.1f} * FT_TO_M),
    App.Rotation()
)
portal_{cid}.ViewObject.ShapeColor = (0.0, 1.0, 0.0)  # Green
portal_group.addObject(portal_{cid})
'''

        return code

    def _generate_adit_geometry(self, freecad_params: Dict, recommendations: Dict) -> str:
        """Generate adit tunnel geometry"""
        return '''
# ============================================================
# ADIT GEOMETRY
# ============================================================

import math

adit_group = doc.addObject("App::DocumentObjectGroup", "Adit")

# Calculate adit direction vector
bearing_rad = math.radians(adit_bearing)
grade_rad = math.atan(adit_grade_pct / 100)

# Direction components (bearing is from north, so sin/cos swapped)
dx = math.sin(bearing_rad)
dy = math.cos(bearing_rad)
dz = -math.tan(grade_rad)  # Downgrade is negative Z

# Adit length in meters
adit_length_m = adit_length_ft * FT_TO_M

# End point of adit
adit_end_x = portal_x + dx * adit_length_m
adit_end_y = portal_y + dy * adit_length_m
adit_end_z = portal_elev * FT_TO_M + dz * adit_length_m

# Adit centerline
adit_centerline = Draft.makeLine(
    Vector(portal_x, portal_y, portal_elev * FT_TO_M),
    Vector(adit_end_x, adit_end_y, adit_end_z)
)
adit_centerline.Label = "AditCenterline"
adit_group.addObject(adit_centerline)

# Adit excavation profile (simplified as box)
adit_w_m = adit_excavation_w_ft * FT_TO_M
adit_h_m = adit_excavation_h_ft * FT_TO_M

# Create adit as extruded rectangle
adit_profile = Part.makeBox(adit_w_m, adit_h_m, adit_length_m)
adit_excavation = doc.addObject("Part::Feature", "AditExcavation")
adit_excavation.Shape = adit_profile

# Position and rotate adit
# Rotation: align Z axis with adit direction
adit_excavation.Placement = App.Placement(
    Vector(portal_x - adit_w_m/2, portal_y, portal_elev * FT_TO_M - adit_h_m/2),
    App.Rotation(Vector(0, 1, 0), math.degrees(grade_rad)) * App.Rotation(Vector(0, 0, 1), -adit_bearing)
)
adit_excavation.ViewObject.Transparency = 50
adit_excavation.ViewObject.ShapeColor = (0.6, 0.4, 0.2)  # Brown
adit_group.addObject(adit_excavation)

'''

    def _generate_collar_geometry(self, freecad_params: Dict) -> str:
        """Generate collar/bulkhead geometry"""
        return '''
# ============================================================
# COLLAR (Bedrock Interface)
# ============================================================

collar_group = doc.addObject("App::DocumentObjectGroup", "Collar")

# Collar is at bedrock interface (using likely depth)
collar_station_m = bedrock_likely_ft * FT_TO_M

# Calculate collar position along adit
collar_x = portal_x + dx * collar_station_m
collar_y = portal_y + dy * collar_station_m
collar_z = portal_elev * FT_TO_M + dz * collar_station_m

# Collar thickness
collar_t_m = collar_thickness_ft * FT_TO_M
collar_w_m = (adit_excavation_w_ft + 2) * FT_TO_M  # Wider than excavation
collar_h_m = (adit_excavation_h_ft + 2) * FT_TO_M  # Taller than excavation

collar_box = Part.makeBox(collar_w_m, collar_t_m, collar_h_m)
collar = doc.addObject("Part::Feature", "Collar")
collar.Shape = collar_box
collar.Placement = App.Placement(
    Vector(collar_x - collar_w_m/2, collar_y, collar_z - collar_h_m/2),
    App.Rotation(Vector(0, 0, 1), -adit_bearing)
)
collar.ViewObject.ShapeColor = (0.5, 0.5, 0.5)  # Gray
collar_group.addObject(collar)

'''

    def _generate_chamber_geometry(self, freecad_params: Dict) -> str:
        """Generate chamber geometry"""
        chambers = freecad_params.get('chambers', [])

        code = '''
# ============================================================
# CHAMBERS
# ============================================================

chamber_group = doc.addObject("App::DocumentObjectGroup", "Chambers")

# Chambers start after collar
chamber_start_m = collar_station_m + collar_thickness_ft * FT_TO_M

'''
        offset = 0
        for ch in chambers:
            ch_id = ch.get('id', 'CH1')
            length = ch.get('length_ft', 24) * 0.3048
            width = ch.get('width_ft', 18) * 0.3048
            height = ch.get('height_ft', 9) * 0.3048
            role = ch.get('role', 'Chamber')

            code += f'''
# {ch_id}: {role}
{ch_id}_box = Part.makeBox({width:.2f}, {length:.2f}, {height:.2f})
{ch_id} = doc.addObject("Part::Feature", "{ch_id}")
{ch_id}.Shape = {ch_id}_box
{ch_id}.Placement = App.Placement(
    Vector(collar_x - {width/2:.2f}, collar_y + {offset:.2f}, collar_z - {height/2:.2f}),
    App.Rotation(Vector(0, 0, 1), -adit_bearing)
)
{ch_id}.ViewObject.ShapeColor = (0.2, 0.4, 0.8)  # Blue
chamber_group.addObject({ch_id})

'''
            offset += length + 2  # 2m spacing between chambers

        return code

    def _generate_layer_organization(self) -> str:
        """Generate layer organization"""
        return '''
# ============================================================
# LAYER ORGANIZATION
# ============================================================

# Create layer groups for CAD organization
clay_zone = doc.addObject("App::DocumentObjectGroup", "Layer_ClayZone")
bedrock_zone = doc.addObject("App::DocumentObjectGroup", "Layer_BedrockZone")
structures = doc.addObject("App::DocumentObjectGroup", "Layer_Structures")

# Add objects to appropriate layers
clay_zone.addObject(adit_group)
bedrock_zone.addObject(collar_group)
bedrock_zone.addObject(chamber_group)
structures.addObject(terrain_group)
structures.addObject(portal_group)

'''


# CLI interface
if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='Generate FreeCAD macro from site inputs')
    parser.add_argument('inputs_json', help='Path to freecad_site_inputs.json')
    parser.add_argument('output_macro', help='Output .FCMacro path')

    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO)

    generator = FreeCADMacroGenerator(args.inputs_json)
    generator.generate_macro(args.output_macro)

    print(f"Generated: {args.output_macro}")
